name: Build Windows App
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Auto Find Folder & Package
        run: |
          $folder = Get-ChildItem -Directory | Select-Object -First 1 -ExpandProperty Name
          cd "$folder"
          npm install
          npm run build
          npm install -g @neutralinojs/neu
          npx nativefier --name "India_Post_Bagging" --platform windows "dist/index.html" dist-win
      - name: Upload Windows Setup
        uses: actions/upload-artifact@v4
        with:
          name: Windows-EXE-App
          path: |
            **/dist-win/*/
            
