name: Build Windows App
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Create Direct Launcher
        run: |
          mkdir win-app
          echo @echo off > win-app\Launch_Portal.bat
          echo start msedge --app="https://netlify.app" >> win-app\Launch_Portal.bat
      - name: Upload Windows Setup
        uses: actions/upload-artifact@v4
        with:
          name: Windows-EXE-App
          path: win-app/
          
